### PR TITLE
Add Docker environment & web demo

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @NetEase-GameAI, @xunings ! 👋 

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can try out your model! We currently implemented the selfie-to-anime model, View it here: https://replicate.ai/netease-gameai/spatchgan-selfie2anime

Do [claim your page here](https://replicate.ai/login/github/?next=/netease-gameai/spatchgan-selfie2anime?published=1) so you can own the page, customise the Example gallery as you like, and we'll feature it on our website and tweet about it too.

In case you're wondering who I am, I'm from [Replicate](https://replicate.ai/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by xunings** [comment]
Hi @CJWBW ,
Thanks for you contribution. The idea of having a running demo and an example of docker config sounds good to me.
Since the repo is owned by NetEase, I need to make sure that this addon is marked as "3rdparty" if merged into main. And I am not able to maintain this replicate module (hopefully not necessary).
Can you move the two additional files (predict.py and cog.yaml) to a separate subdirectory called "./3rdparty/replicate"? I will be fine to merge the pull request then. I may also modify the readme to adjust the position of the replicate link later.

Xuning Shao

**Comment by chenxwh** [comment]
Hi @xunings,

Thank you for your feedback :) sure we can move the files to a subdirectory. 
It is valuable to login with the GitHub account associated with the model on the page to claim the page, so we can feature it on our website too and more people can view and try. Would you prefer if we set the model under your profile, namely  `xunings/spatchgan-selfie2anime` (rather than `netease-gameai/spatchgan-selfie2anime`)? If so, we can push a version to the new url and update the link in README.

Looking forward to hearing what you think :) - I will update the PR with the subdirectory modification accordingly.

**Comment by xunings** [comment]
Hi @CJWBW ,
Just Keep the model under netease-gameai. We will try to claim the page with the corresponding account.
Xuning

**Comment by chenxwh** [comment]
Hi @xunings :),

Sure we will keep the page under netease-gameai then. Just moved the added files to the sub directory as suggested.
Thank you :)

**Review by xunings — APPROVED** [review]

**Pull request merged**
